
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: executables.radius.dev
spec:
  group: radius.dev
  names:
    categories:
    - all
    - radius
    kind: Executable
    listKind: ExecutableList
    plural: executables
    singular: executable
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.executable
      name: Executable
      type: string
    - jsonPath: .spec.args
      name: Args
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ExecutableSpec defines the desired state of an Executable
            properties:
              args:
                description: Launch arguments to be passed to the Executable
                items:
                  type: string
                type: array
              env:
                additionalProperties:
                  type: string
                description: Environment variables to be set for the Executable
                type: object
              envFiles:
                description: Environment variable files to be used for initializing
                  Executable environment
                items:
                  type: string
                type: array
              executable:
                description: Path to Executable binary
                type: string
              replicas:
                default: 1
                description: Number of replicas to launch for the Executable
                maximum: 100
                minimum: 1
                type: integer
              workingDirectory:
                description: The working directory for the Executable
                type: string
            required:
            - executable
            type: object
          status:
            properties:
              finishTimestamp:
                format: date-time
                type: string
              replicas:
                items:
                  properties:
                    exitCode:
                      description: Exit code of a process
                      type: integer
                    logfile:
                      type: string
                    pid:
                      description: The process ID
                      type: integer
                  required:
                  - pid
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
