apiVersion: v2
description: Radius provides a declarative way to manage your infrastructure and applications.
name: radius
# version is the chart version, which will be replaced when this chart is packaged.
version: '0.42.42-dev'
# appVersion is the version of Radius, which will be replaced when this chart is packaged.
appVersion: 'latest'
home: https://radapp.dev
sources:
  - https://github.com/project-radius/radius/tree/main/deploy/Chart
maintainers:
  - name: Radius Authors
    url: https://github.com/project-radius/radius
icon: https://radapp.dev/images/logo.png
keywords:
  - radius
  - iac
  - bicep