apiVersion: v2
name: radius
description: Radius controller for Kubernetes
type: application
# We automate versioning of the chart during publishing.
# The value here is only used for a dev build.
version: '42.42.42-dev'
dependencies:
  - name: radius
    version: '42.42.42-dev'
    repository: "file://radius"
  - name: deployment-engine
    version: '42.42.42-dev'
    repository: "file://deployment-engine"
  - name: ucp
    version: '42.42.42-dev'
    repository: "file://ucpd"
