apiVersion: v2
name: radius
description: Radius controller for Kubernetes
type: application
# We automate versioning of the chart during publishing.
# The value here is only used for a dev build.
version: '42.42.42-dev'
dependencies:
  - name: de
    version: '42.42.42-dev'
    repository: "file://de"
  - name: ucp
    version: '42.42.42-dev'
    repository: "file://ucp"
  - name: rp
    version: '42.42.42-dev'
    repository: "file://rp"
