# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /test/magpiego
    schedule:
      interval: weekly
    groups:
      magpie-go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /test/testrp
    schedule:
      interval: weekly
    groups:
      testrp-go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /typespec
    schedule:
      interval: weekly
    groups:
      typespec:
        applies-to: version-updates
        patterns:
          - "*" # Matches all dependencies
        update-types:
          - patch # Only allow patch updates for regular version updates
