---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: queuemessages.ucp.dev
spec:
  group: ucp.dev
  names:
    kind: QueueMessage
    listKind: QueueMessageList
    plural: queuemessages
    singular: queuemessage
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: QueueMessage is the Schema for QueueMessage API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              contentType:
                description: ContentType represents the content-type of Data.
                type: string
              data:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              dequeueCount:
                description: DequeueCount represents the number of dequeue.
                type: integer
              enqueueAt:
                description: EnqueueAt represents the time when enqueuing the message
                format: date-time
                type: string
              expireAt:
                description: ExpireAt represents the expiry of the message.
                format: date-time
                type: string
            required:
            - contentType
            - data
            - dequeueCount
            - enqueueAt
            - expireAt
            type: object
        type: object
    served: true
    storage: true
