
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: radius-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bicep.dev
  resources:
  - deploymenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bicep.dev
  resources:
  - deploymenttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - bicep.dev
  resources:
  - deploymenttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dapr.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - containercomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - containercomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - containercomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriodaprhttproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - dapriodaprhttproutes/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriodaprhttproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriopubsubtopiccomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - dapriopubsubtopiccomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriopubsubtopiccomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriostatestorecomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - dapriostatestorecomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - dapriostatestorecomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - grpcroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - grpcroutes/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - grpcroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - httproutes/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - mongodbcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - mongodbcomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - mongodbcomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - rabbitmqcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - rabbitmqcomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - rabbitmqcomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - rediscomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - rediscomponents/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - rediscomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - radius.dev
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radius.dev
  resources:
  - resources/finalizers
  verbs:
  - update
- apiGroups:
  - radius.dev
  resources:
  - resources/status
  verbs:
  - get
  - patch
  - update
