{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "radius-controller-cert"}}
{{- $existingWebHookConfig := lookup "admissionregistration.k8s.io/v1" "ValidatingWebhookConfiguration" .Release.Namespace "radius-controller"}}
{{- $ca := genCA "radius-controller-ca" 3650 }}
{{- $cn := printf "radius-controller" }}
{{- $altName1 := printf "webhook-service.%s" .Release.Namespace }}
{{- $altName2 := printf "webhook-service.%s.svc" .Release.Namespace }}
{{- $altName3 := printf "webhook-service.%s.svc.cluster" .Release.Namespace }}
{{- $altName4 := printf "webhook-service.%s.svc.cluster.local" .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2 $altName3 $altName4) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: radius-controller-cert
  labels:
    app: radius-controller
data:
  {{ if $existingSecret }}tls.crt: {{ index $existingSecret.data "tls.crt" }}
  {{ else }}tls.crt: {{ b64enc $cert.Cert }}
  {{ end }}

  {{ if $existingSecret }}tls.key: {{ index $existingSecret.data "tls.key" }}
  {{ else }}tls.key: {{ b64enc $cert.Key }}
  {{ end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: radius-system
      path: /validate-radius-dev-v1alpha1-application
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  failurePolicy: Fail
  name: application-validation.radius.dev
  rules:
  - apiGroups:
    - radius.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: radius-system
      path: /validate-radius-dev-v1alpha1-component
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  failurePolicy: Fail
  name: component-validation.radius.dev
  rules:
  - apiGroups:
    - radius.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: radius-system
      path: /validate-radius-dev-v1alpha1-deployment
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  failurePolicy: Fail
  name: deployment-validation.radius.dev
  rules:
  - apiGroups:
    - radius.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - deployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: radius-system
      path: /validate-radius-dev-v1alpha1-arm
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  failurePolicy: Fail
  name: varm.radius.dev
  rules:
  - apiGroups:
    - radius.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - arms
  sideEffects: None