apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: radius
data:
  controller-config.yaml: |-
    server:
      host: "0.0.0.0"
      port: 9443

    storageProvider:
      provider: "apiserver"
      apiserver:
        context: ""
        namespace: "radius-system"

    secretProvider:
      provider: kubernetes

    queueProvider:
      provider: "apiserver"
      name: "controller"
      apiserver:
        context: ""
        namespace: "radius-system"

    profilerProvider:
      enabled: true
      port: 6060

    ucp:
      kind: kubernetes

    metricsProvider:
      prometheus:
        enabled: true
        path: "/metrics"
        port: 9090

    workerServer:
      port: 3000

    logging:
      level: "info"
      json: true

    {{- if and .Values.global.zipkin .Values.global.zipkin.url }}
    tracerProvider:
      serviceName: "controller"
      zipkin: 
        url: {{ .Values.global.zipkin.url }}
    {{- end }}
    