namespace: Radius.Core
location:
  global: "http://applications-rp.radius-system:5443"
types:
  environments:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  applications:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  recipePacks:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  bicepSettings:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  terraformSettings:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
