apiVersion: v2
name: rp
description: Radius service
type: application
# We automate.... versioning of the chart  during publishing.
# The value here is only used for a dev build.
version: '42.42.42-dev'