---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.0
  name: deploymenttemplates.radapp.io
spec:
  group: radapp.io
  names:
    categories:
    - all
    - radius
    kind: DeploymentTemplate
    listKind: DeploymentTemplateList
    plural: deploymenttemplates
    singular: deploymenttemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of the resource
      jsonPath: .status.phrase
      name: Status
      type: string
    - description: Name of the Bicep file that bicep build is run on
      jsonPath: .status.rootFileName
      name: RootFileName
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        description: DeploymentTemplate is the Schema for the deploymenttemplates
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DeploymentTemplateSpec defines the desired state of DeploymentTemplate
            properties:
              parameters:
                additionalProperties:
                  type: string
                description: Parameters is the ARM JSON parameters for the template.
                type: object
              providerConfig:
                description: ProviderConfig specifies the scope for resources
                type: string
              rootFileName:
                description: |-
                  RootFileName is the name of the Bicep file that
                  `bicep build` is run on.
                type: string
              template:
                description: Template is the ARM JSON manifest that defines the resources
                  to deploy.
                type: string
            type: object
          status:
            description: DeploymentTemplateStatus defines the observed state of DeploymentTemplate
            properties:
              message:
                description: Message is a human-readable description of the status
                  of the Deployment Template.
                type: string
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this DeploymentTemplate.
                format: int64
                type: integer
              operation:
                description: Operation tracks the status of an in-progress provisioning
                  operation.
                properties:
                  operationKind:
                    description: OperationKind describes the type of operation being
                      performed.
                    type: string
                  resumeToken:
                    description: ResumeToken is a token that can be used to resume
                      an in-progress provisioning operation.
                    type: string
                type: object
              outputResources:
                description: OutputResources is a list of the resourceIDs that were
                  created by the template on the last deployment.
                items:
                  type: string
                type: array
              parameters:
                description: Parameters is the ARM JSON parameters for the template.
                type: string
              phrase:
                description: Phrase indicates the current status of the Deployment
                  Template.
                type: string
              providerConfig:
                description: ProviderConfig specifies the scope for resources
                type: string
              resource:
                description: Resource is the resource id of the deployment.
                type: string
              rootFileName:
                description: |-
                  RootFileName is the name of the Bicep file that
                  `bicep build` is run on.
                type: string
              template:
                description: Template is the ARM JSON manifest that defines the resources
                  to deploy.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
