apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-rp-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dynamic-rp
    app.kubernetes.io/part-of: radius
data:
  radius-self-host.yaml: |-
    # Radius configuration file.
    # See https://github.com/radius-project/radius/blob/main/docs/contributing/contributing-code/contributing-code-control-plane/configSettings.md for more information.
    environment:
      name: self-hosted
      roleLocation: "global"
    databaseProvider:
      provider: "apiserver"
      apiserver:
        context: ""
        namespace: "radius-system"
    queueProvider:
      provider: "apiserver"
      name: "dynamic-rp"
      apiserver:
        context: ""
        namespace: "radius-system"
    metricsProvider:
      enabled: true
      serviceName: "dynamic-rp"
      prometheus:
        path: "/metrics"
        port: 9092
    profilerProvider:
      enabled: true
      port: 6062
    secretProvider:
      provider: kubernetes
    server:
      host: "0.0.0.0"
      port: 8082
    workerServer:
      maxOperationConcurrency: 10
      maxOperationRetryCount: 2
    ucp:
      kind: kubernetes
    logging:
      level: "info"
      json: true
    {{- if and .Values.global.zipkin .Values.global.zipkin.url }}
    tracerProvider:
      enabled: true
      serviceName: "dynamic-rp"
      zipkin: 
        url: {{ .Values.global.zipkin.url }}
    {{- end }}
    bicep:
      deleteRetryCount: 20
      deleteRetryDelaySeconds: 60
    terraform:
      path: "/terraform"
