apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: deployment-engine
  name: bicep-deployment-engine
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: deployment-engine
  template:
    metadata:
      labels:
        control-plane: deployment-engine
{{ if .Values.global.rp.provider.azure.podidentity }}
        aadpodidbinding: {{ .Values.global.rp.provider.azure.podidentity }}
{{ end }}
    spec:
      serviceAccountName: deployment-engine-manager
      containers:
      - args:
        - --kubernetes=true
        envFrom:
        - secretRef: 
            name: bicep-deployment-engine
        env:
        - name: ASPNETCORE_URLS
          value: https://+:6443
        - name: kubernetes
          value: "true"
        - name: ASPNETCORE_Kestrel__Endpoints__HttpsPemCertFile__Url
          value: https://+:6443
        - name: ASPNETCORE_Logging__LogLevel__Default
          value: "Debug"
        - name: ASPNETCORE_Kestrel__Endpoints__HttpsPemCertFile__Certificate__Path
          value: /bicep/cert/tls.crt
        - name: ASPNETCORE_Kestrel__Endpoints__HttpsPemCertFile__Certificate__KeyPath
          value: /bicep/cert/tls.key
        image: {{ .Values.global.engine.image }}:{{ .Values.global.engine.tag }}
        name: deployment-engine
        ports:
        - containerPort: 6443
          name: bicep-api
          protocol: TCP
        volumeMounts:
        - name: cert
          mountPath: /bicep/cert
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
      - env:
        - name: ASPNETCORE_URLS
          value: http://+:5000
        image: {{ .Values.global.extensibility.image }}:{{ .Values.global.extensibility.tag }}
        name: bicep-extensibility
        ports:
        - containerPort: 5000
          name: bicepext
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: cert
        secret:
          secretName: bicep-deployment-engine-cert
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Secret
metadata:
  name: bicep-deployment-engine
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: deployment-engine
stringData:
# Configuration for 'Azure' provider functionality
{{ if .Values.global.rp.provider.azure.podidentity }}
  # Enable ARM but without explicit credentials, pod identity will handle it
  SKIP_ARM: 'false'
  ARM_AUTH_METHOD: 'ManagedIdentity'
  ARM_SUBSCRIPTION_ID: {{ .Values.global.rp.provider.azure.subscriptionId }}
  ARM_RESOURCE_GROUP: {{ .Values.global.rp.provider.azure.resourceGroup }}
{{ else if .Values.global.rp.provider.azure.servicePrincipal }}
  # Enable ARM with explicit credentials
  SKIP_ARM: 'false' 
  ARM_AUTH_METHOD: 'ServicePrincipal'
  AZURE_CLIENT_ID: {{ .Values.global.rp.provider.azure.servicePrincipal.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.global.rp.provider.azure.servicePrincipal.clientSecret }}
  AZURE_TENANT_ID: {{ .Values.global.rp.provider.azure.servicePrincipal.tenantId }}
  ARM_SUBSCRIPTION_ID: {{ .Values.global.rp.provider.azure.subscriptionId }}
  ARM_RESOURCE_GROUP: {{ .Values.global.rp.provider.azure.resourceGroup }}
{{ else }}
  # Skip ARM by default. Overwriting this secret will let you set this to false as well as configure credentials
  SKIP_ARM: 'true' 
{{ end }}
# Configuration for AKS integration. We only need this to be able to manipulate pod-identities via ARM.
# This will move to the environment resource eventually.
{{ if .Values.global.rp.aks }}
  K8S_SUBSCRIPTION_ID: {{ .Values.global.rp.aks.subscriptionId }}
  K8S_RESOURCE_GROUP: {{ .Values.global.rp.aks.resourceGroup }}
  K8S_CLUSTER_NAME: {{ .Values.global.rp.aks.clusterName }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: bicep-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 6443
  selector:
    control-plane: deployment-engine
---
apiVersion: v1
kind: Service
metadata:
  name: bicep-extensibility
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    control-plane: deployment-engine