{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: radius
{{- end }}
