baseURL = "https://radapp.dev/"
languageCode = "en-us"
title = "Project Radius"
theme =  "docsy"

disableFastRender = true

# GitHub Information
github_repo = "https://github.com/Azure/radius"
github_subdir = "docs"
github_branch = "main"

# Mounts
[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "../examples"
    target = "content/examples"

# Disable categories & tags
disableKinds = ["taxonomy", "term"]

# Top Nav Bar
[[menu.main]]
    name = "GitHub"
    weight = 40
    url = "https://github.com/Azure/radius"
[[menu.main]]
    name = "Logout"
    weight = 50
    url = "/.auth/logout"

[params]
copyright = "Project Radius"

# Markdown Engine - Allow inline html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# UI Customization
[params.ui]
sidebar_menu_compact = true