namespace: Applications.Core
location:
  global:
    "http://localhost:8080"
types:
  containers:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
  applications:
    apiVersions:
      "2023-10-01-preview":
        schema: {}  
  environments:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
  recipePacks:
   apiVersions:
      "2023-10-01-preview":
        schema: {}
  gateways:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
  secretStores:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
  extenders:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
  volumes:
    apiVersions:
      "2023-10-01-preview":
        schema: {}   
