# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: "Release dev container feature"

on:
  workflow_dispatch:

jobs:
  call-workflow-test:
    uses: ./.github/workflows/devcontainer-feature-test.yaml

  deploy:
    needs:
      - call-workflow-test
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'radius-project/radius' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: "Publish Features"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./deploy/devcontainer-feature/src"
          generate-docs: "false"
          # disable validation due to used preview feature
          disable-schema-validation: "true"
          # We handle tagging ourselves
          disable-repo-tagging: "true"
          # We don't want to include the repo name, being consistent without
          # examples at https://containers.dev/collections
          features-namespace: "radius-project/devcontainer-features"

        env:
          GITHUB_TOKEN: ${{ github.token }}
