name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.1
        env:
          ado_token: "${{ secrets.ADO_AOCTO_BOT_TOKEN }}"
          github_token: "${{ secrets.GH_RAD_CI_BOT_PAT }}"
          ado_organization: "azure-octo"
          ado_project: "Incubations"
          ado_area_path: "Incubations\\Radius"
          ado_iteration_path: "Incubations\\Radius"
          ado_wit: "GitHub Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
