name: Issues Automation

on:
  issues:
    types: [opened]

jobs:
  customer:
    name: Add a label if Issue created by customer
    runs-on: [self-hosted,1ES.Pool=1ES-Radius ]
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RAD_CI_BOT_PAT }}
    steps:
      - name: Add label if author in preview team
        env:
          ISSUE: ${{ github.event.issue.html_url }}
          AUTHOR: ${{ github.actor }}
        run: |
          MEMBERS=$(gh api orgs/project-radius/teams/Radius-Preview/members | jq -r '.[] | .login')
          ADMINS=$(gh api orgs/project-radius/teams/Radius-Admin/members | jq -r '.[] | .login')
          for USER in $MEMBERS; do
            if [[ "$USER" == "$AUTHOR" ]]; then
              ISADMIN=false
              for ADMIN in $ADMINS; do
                if [[ "$USER" == "$ADMIN" ]]; then
                  echo "$USER is an admin, skipping"
                  ISADMIN=true
                fi
              done
              if [[ "$ISADMIN" == "false" ]]; then
                echo "Adding label for issue $ISSUE"
                gh issue edit $ISSUE --add-label "customer-issue"
              fi
            fi
          done
  trigger-tests:
    name: Trigger CI/CD tests
    runs-on: [ self-hosted, 1ES.Pool=1ES-Radius ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # required to make the script available for next step
      - name: Comment analyzer
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
          script: |
            const script = require('./.github/scripts/test-trigger.js')
            await script({github, context})
