name: static-website

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'test/**'
      - 'cmd/cli/**'
      - 'cmd/docgen/**'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'docs/**'
      - 'test/**'
      - 'cmd/cli/**'
      - 'cmd/docgen/**'
      - '.github/workflows/**'

jobs:
  build_and_deploy_docs:
    name: Build and Deploy Job
    continue-on-error: true
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    env:
      GOVER: '^1.17'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Setup Docsy
        run: cd docs && git submodule update --init --recursive && sudo npm install -D --save autoprefixer && sudo npm install -D --save postcss-cli
      - name: Generate CLI Docs
        run: go run ./cmd/docgen/main.go ./docs/content/reference/cli
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        env:
          HUGO_ENV: production
          HUGO_VERSION: "0.74.3"
        with:
          azure_static_web_apps_api_token: ${{ secrets.DOCS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          skip_deploy_on_missing_secrets: true
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "docs" # App source code path
          api_location: "docs/api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          app_build_command: "hugo && cp ./api/routes.json ./public/routes.json"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.DOCS_TOKEN }}
          skip_deploy_on_missing_secrets: true
          action: "close"
