# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Validate Bicep Code
on:
  pull_request:
    branches:
      - main
      - release/*

concurrency:
  # Cancel the previously triggered build for only PR build.
  group: bicep-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Validate Bicep Code
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Clone docs repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
          repository: project-radius/docs
          path: temp/project-radius/docs
          ref: edge
      - name: Clone samples repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
          repository: project-radius/samples
          path: temp/project-radius/samples
          ref: edge
      - name: Setup Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: az CLI login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SP_TESTS_APPID }} \
            --password ${{ secrets.AZURE_SP_TESTS_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SP_TESTS_TENANTID }}
      - name: Parse release version and set environment variables
        run: python ./.github/scripts/get_release_version.py
      - name: Download rad-bicep-corerp
        run: |
          ./.github/scripts/curl-with-retries.sh https://get.radapp.dev/tools/bicep-extensibility/0.17/linux-x64/rad-bicep --output rad-bicep-corerp
          chmod +x rad-bicep-corerp
          ./rad-bicep-corerp --version
      - name: Verify Bicep files
        run: ./build/validate-bicep.sh
        env:
          BICEP_PATH: .
