# ------------------------------------------------------------
# Copyright 2023 The Radius Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

name: Validate Bicep Code
on:
  # Enable manual trigger
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*

permissions:
  id-token: write # Required for requesting the JWT

env:
  # Local Docker registry name
  LOCAL_REGISTRY_NAME: "radius-registry"
  # Local Docker registry server
  LOCAL_REGISTRY_SERVER: "localhost"
  # Local Docker registry port
  LOCAL_REGISTRY_PORT: "5000"

concurrency:
  # Cancel the previously triggered build for only PR build.
  group: bicep-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Validate Bicep Code
    runs-on: ubuntu-latest
    steps:
      - name: Setup and verify bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Create a temporary file system 
        run:
          mkdir tmp-radius-bicep-extension
      - name: Publish bicep types 
        run: | 
          bicep publish-extension ./bicep-types-radius/generated/index.json --target ./tmp-radius-bicep-extension/radius.tgz 
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Modify bicepconfig.json
        run: |
          # Add credential preference to the bicepconfig.json file
          jq '.extensions.radius = "./tmp-radius-bicep-extension/radius.tgz"' bicepconfig.json > tmp.json && mv tmp.json bicepconfig.json
      - name: Print updated bicepconfig.json
        run: cat bicepconfig.json
      - name: Verify Bicep files
        run: ./build/validate-bicep.sh
        env:
          BICEP_PATH: 'bicep'
