# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Validate Radius Installers
on:
  pull_request:
    paths:
      - "deploy/install.ps1"

concurrency:
  # Cancel the previously triggered build for only PR build.
  group: rad-installer-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  verify-installers:
    name: Validate Installers
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installer test script
        shell: powershell
        run: "deploy/test-pwsh-install.ps1"
