# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  #pull_request:
  #  paths:
  #    - "deploy/devcontainer-feature/**"
  #    - ".github/workflows/devcontainer-feature-test.yaml"
  #  branches:
  #    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: "./deploy/devcontainer-feature/src"
