name: website

on:
  push:
    branches:
      - release/0.7
    paths:
      - 'docs/**'
      - 'test/**'
      - 'cmd/rad/**'
      - 'cmd/docgen/**'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'docs/**'
      - 'test/**'
      - 'cmd/rad/**'
      - 'cmd/docgen/**'
      - '.github/workflows/**'

jobs:
  build_and_deploy_docs:
    name: Build and Deploy Website
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GOVER: '^1.17'
      TUTORIAL_PATH: './docs/content/user-guides/tutorials/'
      CODE_ZIP_PATH: './docs/static/tutorial/'
      HUGO_ENV: production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.74.3
          extended: true
      - name: Setup Docsy
        run: cd docs && git submodule update --init --recursive && sudo npm install -D --save autoprefixer && sudo npm install -D --save postcss-cli
      - name: Generate CLI Docs
        run: go run ./cmd/docgen/main.go ./docs/content/reference/cli
      - name: Generate Code ZIP Packages
        run: mkdir -p $CODE_ZIP_PATH && for tutorial in $TUTORIAL_PATH*; do if [ -d "${tutorial}/code" ]; then cp -r $tutorial/code ./$(basename $tutorial) && zip -r $CODE_ZIP_PATH$(basename $tutorial).zip ./$(basename $tutorial) ; fi; done
      - name: Build Site
        run: cd docs && hugo
      - name: Deploy to WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: radius
          publish-profile: ${{ secrets.DOCS_SITE_PUBLISHPROFILE }}
          package: "./docs/public/"

  build_docs:
    name: Build Website
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      GOVER: '^1.17'
      TUTORIAL_PATH: './docs/content/getting-started/tutorial/'
      CODE_ZIP_PATH: './docs/static/tutorial/'
      HUGO_ENV: production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.74.3
          extended: true
      - name: Setup Docsy
        run: cd docs && git submodule update --init --recursive && sudo npm install -D --save autoprefixer && sudo npm install -D --save postcss-cli
      - name: Generate CLI Docs
        run: go run ./cmd/docgen/main.go ./docs/content/reference/cli
      - name: Generate Code ZIP Packages
        run: mkdir -p $CODE_ZIP_PATH && for tutorial in $TUTORIAL_PATH*; do if [ -d "${tutorial}/code" ]; then cp -r $tutorial/code ./$(basename $tutorial) && zip -r $CODE_ZIP_PATH$(basename $tutorial).zip ./$(basename $tutorial) ; fi; done
      - name: Build Site
        run: cd docs && hugo
